POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30,
  "phone": "01012345678",
  "email": "test@gmail.com"
}

###

GET http://localhost:3000/users/1
Content-Type: application/json
